### ISSUE TITLE
error and crash

### ISSUE THREAD

**Issue by NeluQi** [capacitor-community/file-opener#40]
![image](https://github.com/capacitor-community/file-opener/assets/16963395/e3e7ea7b-747f-48a9-9eb0-70125f3d4052)

    "@capacitor-community/file-opener": "1.0.4",

2023-05-18 22:31:24.747 18629-18629/com.sinfo.client I/Toast: show: isActivityContext = true
2023-05-18 22:31:24.754 18629-18629/com.sinfo.client I/Capacitor/Console: File: http://192.168.0.148:8080/ - Line 230 - Msg: undefined
2023-05-18 22:31:24.755 18629-18629/com.sinfo.client V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 89564398, pluginId: Filesystem, methodName: getUri
2023-05-18 22:31:24.755 18629-18629/com.sinfo.client V/Capacitor: callback: 89564398, pluginId: Filesystem, methodName: getUri, methodData: {"path":"SINFO\/карта-16.05.2023.12.20.11.png","directory":"DOCUMENTS"}
2023-05-18 22:31:24.821 18629-18629/com.sinfo.client I/Capacitor/Console: File: http://192.168.0.148:8080/js/app.js - Line 24716 - Msg: openFile [object Object] карта-16.05.2023.12.20.11.png
2023-05-18 22:31:24.823 18629-18629/com.sinfo.client I/Capacitor/Console: File: http://192.168.0.148:8080/js/app.js - Line 24723 - Msg: openFile [object Object]
2023-05-18 22:31:24.942 18629-18629/com.sinfo.client V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 89564399, pluginId: FileOpener, methodName: open
2023-05-18 22:31:24.942 18629-18629/com.sinfo.client V/Capacitor: callback: 89564399, pluginId: FileOpener, methodName: open, methodData: {"filePath":{"uri":"file:\/\/\/storage\/emulated\/0\/Documents\/SINFO\/%D0%BA%D0%B0%D1%80%D1%82%D0%B0-16.05.2023.12.20.11.png"}}
2023-05-18 22:31:24.943 18629-23794/com.sinfo.client E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:767)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.ryltsov.alex.plugins.file.opener.FileOpenerPlugin.open(FileOpenerPlugin.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:767) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2023-05-18 22:31:24.945 18629-23794/com.sinfo.client E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.sinfo.client, PID: 18629
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:776)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:767)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.ryltsov.alex.plugins.file.opener.FileOpenerPlugin.open(FileOpenerPlugin.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:767) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2023-05-18 22:31:24.958 18629-23794/com.sinfo.client W/om.sinfo.clien: Attempt to remove non-JNI local reference, dumping thread
2023-05-18 22:31:25.013 18629-23794/com.sinfo.client I/Process: Sending signal. PID: 18629 SIG: 9
2023-05-18 22:31:26.310 28515-28515/? I/om.sinfo.clien: Late-enabling -Xcheck:jni
2023-05-18 22:31:26.362 28515-28515/? I/om.sinfo.clien: Unquickening 26 vdex files!
2023-05-18 22:31:26.387 28515-28515/? D/ActivityThread: setConscryptValidator
2023-05-18 22:31:26.387 28515-28515/? D/ActivityThread: setConscryptValidator - put
2023-05-18 22:31:26.425 28515-28515/com.sinfo.client D/ActivityThread: handleBindApplication()++ app=com.sinfo.client
2023-05-18 22:31:26.443 28515-28515/com.sinfo.client I/om.sinfo.clien: The ClassLoaderContext is a special shared library.
2023-05-18 22:31:26.743 28515-28515/com.sinfo.client D/LoadedApk: LoadedApk::makeApplication() appContext=android.app.ContextImpl@cb9c80 appContext.mOpPackageName=com.sinfo.client appContext.mBasePackageName=com.sinfo.client appContext.mPackageInfo=android.app.LoadedApk@b60d2b9
2023-05-18 22:31:26.743 28515-28515/com.sinfo.client D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2023-05-18 22:31:26.771 28515-28515/com.sinfo.client D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2023-05-18 22:31:26.807 28515-28515/com.sinfo.client D/ActivityThread: handleBindApplication() -- skipGraphicsSupport=false
2023-05-18 22:31:26.811 28515-28515/com.sinfo.client D/AndroidRuntime: Shutting down VM
2023-05-18 22:31:26.813 28515-28515/com.sinfo.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sinfo.client, PID: 28515
    java.lang.RuntimeException: Unable to start service com.davidbriglio.foreground.ForegroundService@b7db944 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4805)
        at android.app.ActivityThread.access$2100(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8645)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at com.davidbriglio.foreground.ForegroundService.onStartCommand(ForegroundService.java:16)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4787)
        at android.app.ActivityThread.access$2100(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8645) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 

  await FileOpener.open({
        filePath: ffpath,
      });

**Comment by NeluQi** [comment]
I'm an idiot, I sent an object instead of a path

await FileOpener.open({
filePath: ffpath.uri,
});
solved my problem
